---
server:
    install: '1'
    timezone: Europe/Amsterdam
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: dev.hacktober.io, ip: 192.168.31.37, memory: '512', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /vagrant/web
    servername: dev.hacktober.io
mysql:
    install: '1'
    root_password: r00t!
    database: hacktoberfest
    user: hacktober
    password: h4cktheworld
    dump: ''
redis:
    install: '1'
    port: '6379'
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-mysql]

github:
    client_id: 00000000000000000000
    client_secret: 0000000000000000000000000000000000000
    callback_url: http://dev.hacktober.io/app_dev.php/connect/github